[project]
name = "cmugpt-agent"
revision = "1.0"

[profiles.default]
OIDC_CLIENT_ID = { description = "Keycloak OIDC client ID", required = true }
OIDC_CLIENT_SECRET = { description = "Keycloak OIDC client secret", required = true }
# DATABASE_URL = { description = "Cloud database string for Kennel", required = true }

[profiles.preview] 

[providers]
local = "dotenv://.env"
vault = "vault://secrets2.scottylabs.org/secret"

[profiles.prod]
MCP_SERVER_URL = { description = "MCP Server URL" }
OPENROUTER_API_KEY = { description = "OpenRouter API Key" }

[profiles.dev]
MCP_SERVER_URL = { providers = ["local"] }
OPENROUTER_API_KEY = { providers = ["local"] }